# Generated by Django 5.2.2 on 2025-06-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='students_departm_bebd12_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_major_i_cd8e25_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='students_account_a3374b_idx',
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='students_departm_bebd12_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['major'], name='students_major_i_cd8e25_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['account'], name='students_account_a3374b_idx'),
        ),
    ]
