# Generated by Django 5.2.2 on 2025-06-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturers', '0001_initial'),
        ('rooms', '0001_initial'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('class_student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.CharField(default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_status', models.CharField(default='auto', max_length=20)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'Class Student',
                'verbose_name_plural': 'Class Students',
                'db_table': 'class_students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('repeat_weekly', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QRCheckin',
            fields=[
                ('qr_checkin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qr_code', models.CharField(max_length=255)),
                ('expire_at', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(max_length=1)),
                ('usage_count', models.IntegerField()),
                ('max_usage', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
                ('used_by_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.schedule')),
            ],
            options={
                'verbose_name': 'QR Checkin',
                'verbose_name_plural': 'QR Checkins',
                'db_table': 'qr_checkins',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['department_id'], name='classes_departm_98bb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year_id'], name='classes_academi_c56e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['class_id'], name='class_stude_class_i_05f053_idx'),
        ),
        migrations.AddIndex(
            model_name='classstudent',
            index=models.Index(fields=['student_id'], name='class_stude_student_a2eaf8_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['class_id'], name='schedules_class_i_bf9668_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['subject_id'], name='schedules_subject_3d2967_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['room_id'], name='schedules_room_id_3a02e7_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['schedule_id'], name='qr_checkins_schedul_624ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['created_by'], name='qr_checkins_created_7e5fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcheckin',
            index=models.Index(fields=['used_by_student_id'], name='qr_checkins_used_by_068bf5_idx'),
        ),
    ]
