# Generated by Django 5.2.2 on 2025-06-07 06:04

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_code', models.CharField(default=accounts.models.generate_random_code, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permisson',
            fields=[
                ('permission_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=100)),
                ('read', models.CharField(max_length=1)),
                ('insert', models.CharField(max_length=1)),
                ('update', models.CharField(max_length=1)),
                ('delete', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.CharField(default='1', max_length=1)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now_add=True)),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='account_avatars/')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.CharField(default='0', max_length=1)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified_email', models.CharField(default='0', max_length=1)),
                ('user_type', models.CharField(max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'managed': True,
            },
        ),
    ]
