# Generated by Django 5.2.2 on 2025-06-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0002_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('avatar_url', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'db_table': 'lecturers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LecturerSubject',
            fields=[
                ('lecturer_subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Lecturer Subject',
                'verbose_name_plural': 'Lecturer Subjects',
                'db_table': 'lecturer_subjects',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['account_id'], name='lecturers_account_9bca51_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturer',
            index=models.Index(fields=['department_id'], name='lecturers_departm_77f381_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturersubject',
            index=models.Index(fields=['subject_id'], name='lecturer_su_subject_d130f9_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturersubject',
            index=models.Index(fields=['lecturer_id'], name='lecturer_su_lecture_068b11_idx'),
        ),
    ]
